version: "2"
linters:
  enable:
    - asciicheck
    - goconst
    - gocritic
    - gosec
    - misspell
    - mnd
    - prealloc
    - revive
    - unconvert
    - usetesting
  settings:
    gocritic:
      disabled-checks:
        - paramTypeCombine
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    govet:
      disable:
        - shadow
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
